name: Main workflow for numero-unico-processo

on:
  pull_request:
    # Run on to branches with an open PR
    branches:
      - "*"
  push:
    branches:
      - master
  
jobs:
  build:
    name: Node.js LTS on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      # Install node_modules
      - run: yarn install --frozen-lockfile
      # Run unit tests
      - run: yarn test
      # Run unit tests with coverage
      - run: yarn coverage
